Blockly.Blocks['thingspeak_update'] = {
  init: function() {   
  this.appendValueInput("key")
      .setCheck("String")
      .setAlign(Blockly.ALIGN_RIGHT)
      .appendField("Key");
  this.appendValueInput("field1")
      .setCheck("String")
      .setAlign(Blockly.ALIGN_RIGHT)
      .appendField("field1");
  this.appendValueInput("field2")
      .setCheck("String")
      .setAlign(Blockly.ALIGN_RIGHT)
      .appendField("field2");
  this.appendValueInput("field3")
      .setCheck("String")
      .setAlign(Blockly.ALIGN_RIGHT)
      .appendField("field3");  
  this.appendValueInput("field4")
      .setCheck("String")
      .setAlign(Blockly.ALIGN_RIGHT)
      .appendField("field4");
  this.appendValueInput("field5")
      .setCheck("String")
      .setAlign(Blockly.ALIGN_RIGHT)
      .appendField("field5");
  this.appendValueInput("field6")
      .setCheck("String")
      .setAlign(Blockly.ALIGN_RIGHT)
      .appendField("field6");  
  this.appendValueInput("field7")
      .setCheck("String")
      .setAlign(Blockly.ALIGN_RIGHT)
      .appendField("field7");
  this.appendValueInput("field8")
      .setCheck("String")
      .setAlign(Blockly.ALIGN_RIGHT)
      .appendField("field8");  
  this.setPreviousStatement(true);
  this.setNextStatement(true);
  this.setTooltip('');
  this.setColour(65);
  this.setHelpUrl(mainUrl + 'basic/blockly/blockly-information.html' + utmUrl);
  }
};
