Blockly.Blocks['speak_setting_sample_fustyles'] = {
  init: function () {
    this.appendDummyInput()
      .appendField(Blockly.Msg.WEBDUINO_SPEAK_LANG)
      .appendField(new Blockly.FieldDropdown([
        [Blockly.Msg.WEBDUINO_SPEAK_TW, "zh-TW"],
        [Blockly.Msg.WEBDUINO_SPEAK_US, "en-US"],
        [Blockly.Msg.WEBDUINO_SPEAK_JP, "ja-JP"],
        [Blockly.Msg.WEBDUINO_SPEAK_KR, "ko-KR"],
        [Blockly.Msg.WEBDUINO_SPEAK_VI, "vi-VN"],      
        [Blockly.Msg.WEBDUINO_SPEAK_ES, "es-ES"],
        [Blockly.Msg.WEBDUINO_SPEAK_FR, "fr-FR"],
        [Blockly.Msg.WEBDUINO_SPEAK_IT, "it-IT"],
        [Blockly.Msg.WEBDUINO_SPEAK_af-ZA,"af-ZA"],
        [Blockly.Msg.WEBDUINO_SPEAK_am-ET,"am-ET"],
        [Blockly.Msg.WEBDUINO_SPEAK_hy-AM,"hy-AM"],
        [Blockly.Msg.WEBDUINO_SPEAK_az-AZ,"az-AZ"],
        [Blockly.Msg.WEBDUINO_SPEAK_id-ID,"id-ID"],
        [Blockly.Msg.WEBDUINO_SPEAK_ms-MY,"ms-MY"],
        [Blockly.Msg.WEBDUINO_SPEAK_bn-BD,"bn-BD"],
        [Blockly.Msg.WEBDUINO_SPEAK_bn-IN,"bn-IN"],
        [Blockly.Msg.WEBDUINO_SPEAK_ca-ES,"ca-ES"],
        [Blockly.Msg.WEBDUINO_SPEAK_cs-CZ,"cs-CZ"],
        [Blockly.Msg.WEBDUINO_SPEAK_da-DK,"da-DK"],
        [Blockly.Msg.WEBDUINO_SPEAK_de-DE,"de-DE"],
        [Blockly.Msg.WEBDUINO_SPEAK_en-AU,"en-AU"],
        [Blockly.Msg.WEBDUINO_SPEAK_en-CA,"en-CA"],
        [Blockly.Msg.WEBDUINO_SPEAK_en-GH,"en-GH"],
        [Blockly.Msg.WEBDUINO_SPEAK_en-GB,"en-GB"],
        [Blockly.Msg.WEBDUINO_SPEAK_en-IN,"en-IN"],
        [Blockly.Msg.WEBDUINO_SPEAK_en-IE,"en-IE"],
        [Blockly.Msg.WEBDUINO_SPEAK_en-KE,"en-KE"],
        [Blockly.Msg.WEBDUINO_SPEAK_en-NZ,"en-NZ"],
        [Blockly.Msg.WEBDUINO_SPEAK_en-NG,"en-NG"],
        [Blockly.Msg.WEBDUINO_SPEAK_en-PH,"en-PH"],
        [Blockly.Msg.WEBDUINO_SPEAK_en-ZA,"en-ZA"],
        [Blockly.Msg.WEBDUINO_SPEAK_en-TZ,"en-TZ"],
        [Blockly.Msg.WEBDUINO_SPEAK_en-US,"en-US"],
        [Blockly.Msg.WEBDUINO_SPEAK_es-AR,"es-AR"],
        [Blockly.Msg.WEBDUINO_SPEAK_es-BO,"es-BO"],
        [Blockly.Msg.WEBDUINO_SPEAK_es-CL,"es-CL"],
        [Blockly.Msg.WEBDUINO_SPEAK_es-CO,"es-CO"],
        [Blockly.Msg.WEBDUINO_SPEAK_es-CR,"es-CR"],
        [Blockly.Msg.WEBDUINO_SPEAK_es-EC,"es-EC"],
        [Blockly.Msg.WEBDUINO_SPEAK_es-SV,"es-SV"],
        [Blockly.Msg.WEBDUINO_SPEAK_es-ES,"es-ES"],
        [Blockly.Msg.WEBDUINO_SPEAK_es-US,"es-US"],
        [Blockly.Msg.WEBDUINO_SPEAK_es-GT,"es-GT"],
        [Blockly.Msg.WEBDUINO_SPEAK_es-HN,"es-HN"],
        [Blockly.Msg.WEBDUINO_SPEAK_es-MX,"es-MX"],
        [Blockly.Msg.WEBDUINO_SPEAK_es-NI,"es-NI"],
        [Blockly.Msg.WEBDUINO_SPEAK_es-PA,"es-PA"],
        [Blockly.Msg.WEBDUINO_SPEAK_es-PY,"es-PY"],
        [Blockly.Msg.WEBDUINO_SPEAK_es-PE,"es-PE"],
        [Blockly.Msg.WEBDUINO_SPEAK_es-PR,"es-PR"],
        [Blockly.Msg.WEBDUINO_SPEAK_es-DO,"es-DO"],
        [Blockly.Msg.WEBDUINO_SPEAK_es-UY,"es-UY"],
        [Blockly.Msg.WEBDUINO_SPEAK_es-VE,"es-VE"],
        [Blockly.Msg.WEBDUINO_SPEAK_eu-ES,"eu-ES"],
        [Blockly.Msg.WEBDUINO_SPEAK_fil-PH,"fil-PH"],
        [Blockly.Msg.WEBDUINO_SPEAK_fr-CA,"fr-CA"],
        [Blockly.Msg.WEBDUINO_SPEAK_fr-FR,"fr-FR"],
        [Blockly.Msg.WEBDUINO_SPEAK_gl-ES,"gl-ES"],
        [Blockly.Msg.WEBDUINO_SPEAK_ka-GE,"ka-GE"],
        [Blockly.Msg.WEBDUINO_SPEAK_gu-IN,"gu-IN"],
        [Blockly.Msg.WEBDUINO_SPEAK_hr-HR,"hr-HR"],
        [Blockly.Msg.WEBDUINO_SPEAK_zu-ZA,"zu-ZA"],
        [Blockly.Msg.WEBDUINO_SPEAK_is-IS,"is-IS"],
        [Blockly.Msg.WEBDUINO_SPEAK_it-IT,"it-IT"],
        [Blockly.Msg.WEBDUINO_SPEAK_jv-ID,"jv-ID"],
        [Blockly.Msg.WEBDUINO_SPEAK_kn-IN,"kn-IN"],
        [Blockly.Msg.WEBDUINO_SPEAK_km-KH,"km-KH"],
        [Blockly.Msg.WEBDUINO_SPEAK_lo-LA,"lo-LA"],
        [Blockly.Msg.WEBDUINO_SPEAK_lv-LV,"lv-LV"],
        [Blockly.Msg.WEBDUINO_SPEAK_lt-LT,"lt-LT"],
        [Blockly.Msg.WEBDUINO_SPEAK_hu-HU,"hu-HU"],
        [Blockly.Msg.WEBDUINO_SPEAK_ml-IN,"ml-IN"],
        [Blockly.Msg.WEBDUINO_SPEAK_mr-IN,"mr-IN"],
        [Blockly.Msg.WEBDUINO_SPEAK_nl-NL,"nl-NL"],
        [Blockly.Msg.WEBDUINO_SPEAK_ne-NP,"ne-NP"],
        [Blockly.Msg.WEBDUINO_SPEAK_nb-NO,"nb-NO"],
        [Blockly.Msg.WEBDUINO_SPEAK_pl-PL,"pl-PL"],
        [Blockly.Msg.WEBDUINO_SPEAK_pt-BR,"pt-BR"],
        [Blockly.Msg.WEBDUINO_SPEAK_pt-PT,"pt-PT"],
        [Blockly.Msg.WEBDUINO_SPEAK_ro-RO,"ro-RO"],
        [Blockly.Msg.WEBDUINO_SPEAK_si-LK,"si-LK"],
        [Blockly.Msg.WEBDUINO_SPEAK_sk-SK,"sk-SK"],
        [Blockly.Msg.WEBDUINO_SPEAK_sl-SI,"sl-SI"],
        [Blockly.Msg.WEBDUINO_SPEAK_su-ID,"su-ID"],
        [Blockly.Msg.WEBDUINO_SPEAK_sw-TZ,"sw-TZ"],
        [Blockly.Msg.WEBDUINO_SPEAK_sw-KE,"sw-KE"],
        [Blockly.Msg.WEBDUINO_SPEAK_fi-FI,"fi-FI"],
        [Blockly.Msg.WEBDUINO_SPEAK_sv-SE,"sv-SE"],
        [Blockly.Msg.WEBDUINO_SPEAK_ta-IN,"ta-IN"],
        [Blockly.Msg.WEBDUINO_SPEAK_ta-SG,"ta-SG"],
        [Blockly.Msg.WEBDUINO_SPEAK_ta-LK,"ta-LK"],
        [Blockly.Msg.WEBDUINO_SPEAK_ta-MY,"ta-MY"],
        [Blockly.Msg.WEBDUINO_SPEAK_te-IN,"te-IN"],
        [Blockly.Msg.WEBDUINO_SPEAK_vi-VN,"vi-VN"],
        [Blockly.Msg.WEBDUINO_SPEAK_tr-TR,"tr-TR"],
        [Blockly.Msg.WEBDUINO_SPEAK_ur-PK,"ur-PK"],
        [Blockly.Msg.WEBDUINO_SPEAK_ur-IN,"ur-IN"],
        [Blockly.Msg.WEBDUINO_SPEAK_el-GR,"el-GR"],
        [Blockly.Msg.WEBDUINO_SPEAK_bg-BG,"bg-BG"],
        [Blockly.Msg.WEBDUINO_SPEAK_ru-RU,"ru-RU"],
        [Blockly.Msg.WEBDUINO_SPEAK_sr-RS,"sr-RS"],
        [Blockly.Msg.WEBDUINO_SPEAK_uk-UA,"uk-UA"],
        [Blockly.Msg.WEBDUINO_SPEAK_he-IL,"he-IL"],
        [Blockly.Msg.WEBDUINO_SPEAK_ar-IL,"ar-IL"],
        [Blockly.Msg.WEBDUINO_SPEAK_ar-JO,"ar-JO"],
        [Blockly.Msg.WEBDUINO_SPEAK_ar-AE,"ar-AE"],
        [Blockly.Msg.WEBDUINO_SPEAK_ar-BH,"ar-BH"],
        [Blockly.Msg.WEBDUINO_SPEAK_ar-DZ,"ar-DZ"],
        [Blockly.Msg.WEBDUINO_SPEAK_ar-SA,"ar-SA"],
        [Blockly.Msg.WEBDUINO_SPEAK_ar-IQ,"ar-IQ"],
        [Blockly.Msg.WEBDUINO_SPEAK_ar-KW,"ar-KW"],
        [Blockly.Msg.WEBDUINO_SPEAK_ar-MA,"ar-MA"],
        [Blockly.Msg.WEBDUINO_SPEAK_ar-TN,"ar-TN"],
        [Blockly.Msg.WEBDUINO_SPEAK_ar-OM,"ar-OM"],
        [Blockly.Msg.WEBDUINO_SPEAK_ar-PS,"ar-PS"],
        [Blockly.Msg.WEBDUINO_SPEAK_ar-QA,"ar-QA"],
        [Blockly.Msg.WEBDUINO_SPEAK_ar-LB,"ar-LB"],
        [Blockly.Msg.WEBDUINO_SPEAK_ar-EG,"ar-EG"],
        [Blockly.Msg.WEBDUINO_SPEAK_fa-IR,"fa-IR"],
        [Blockly.Msg.WEBDUINO_SPEAK_hi-IN,"hi-IN"],
        [Blockly.Msg.WEBDUINO_SPEAK_th-TH,"th-TH"],
        [Blockly.Msg.WEBDUINO_SPEAK_ko-KR,"ko-KR"],
        [Blockly.Msg.WEBDUINO_SPEAK_cmn-Hant-TW,"cmn-Hant-TW"],
        [Blockly.Msg.WEBDUINO_SPEAK_yue-Hant-HK,"yue-Hant-HK"],
        [Blockly.Msg.WEBDUINO_SPEAK_ja-JP,"ja-JP"],
        [Blockly.Msg.WEBDUINO_SPEAK_cmn-Hans-HK,"cmn-Hans-HK"],
        [Blockly.Msg.WEBDUINO_SPEAK_cmn-Hans-CN,"cmn-Hans-CN"]      
      ]), "lang_")
      .appendField(Blockly.Msg.WEBDUINO_SPEAK_VOLUME)
      .appendField(new Blockly.FieldDropdown([
        ["1", "1"],
        ["0.9", "0.9"],
        ["0.8", "0.8"],
        ["0.7", "0.7"],
        ["0.6", "0.6"],
        ["0.5", "0.5"],
        ["0.4", "0.4"],
        ["0.3", "0.3"],
        ["0.2", "0.3"],
        ["0.1", "0.1"],
        ["0", "0"]
      ]), "volume_")
      .appendField(Blockly.Msg.WEBDUINO_SPEAK_PITCH)
      .appendField(new Blockly.FieldDropdown([
        [Blockly.Msg.WEBDUINO_SPEAK_P20, "2"],
        [Blockly.Msg.WEBDUINO_SPEAK_P15, "1.5"],
        [Blockly.Msg.WEBDUINO_SPEAK_P10, "1"],
        [Blockly.Msg.WEBDUINO_SPEAK_P05, "0.5"],
        [Blockly.Msg.WEBDUINO_SPEAK_P01, "0.1"]
      ]), "pitch_")
      .appendField(Blockly.Msg.WEBDUINO_SPEAK_RATE)
      .appendField(new Blockly.FieldDropdown([
        [Blockly.Msg.WEBDUINO_SPEAK_R20, "2"],
        [Blockly.Msg.WEBDUINO_SPEAK_R15, "1.5"],
        [Blockly.Msg.WEBDUINO_SPEAK_R10, "1"],
        [Blockly.Msg.WEBDUINO_SPEAK_R07, "0.7"],
        [Blockly.Msg.WEBDUINO_SPEAK_R05, "0.5"]
      ]), "rate_");
    this.setInputsInline(true);
    this.setOutput(true, null);
    this.setTooltip('');
    this.setColour(270);
    this.setHelpUrl(mainUrl + 'useful/component/buzzer-clock.html' + utmUrl); 
  }
};
