Blockly.JavaScript['matrix_led'] = function(block) {
  alert(block.getFieldValue('L1'));
  var L1 = (block.getFieldValue('L1') == 'TRUE')?"1":"0";
  var L2 = (block.getFieldValue('L2') == 'TRUE')?"1":"0";
  var L3 = (block.getFieldValue('L3') == 'TRUE')?"1":"0";
  var L4 = (block.getFieldValue('L4') == 'TRUE')?"1":"0";
  var L5 = (block.getFieldValue('L5') == 'TRUE')?"1":"0";
  var L6 = (block.getFieldValue('L6') == 'TRUE')?"1":"0";
  var L7 = (block.getFieldValue('L7') == 'TRUE')?"1":"0";
  var L8 = (block.getFieldValue('L8') == 'TRUE')?"1":"0";
  var L9 = (block.getFieldValue('L9') == 'TRUE')?"1":"0";
  var L10 = (block.getFieldValue('L10') == 'TRUE')?"1":"0";
  var L11 = (block.getFieldValue('L11') == 'TRUE')?"1":"0";
  var L12 = (block.getFieldValue('L12') == 'TRUE')?"1":"0";
  var L13 = (block.getFieldValue('L13') == 'TRUE')?"1":"0";
  var L14 = (block.getFieldValue('L14') == 'TRUE')?"1":"0";
  var L15 = (block.getFieldValue('L15') == 'TRUE')?"1":"0";
  var L16 = (block.getFieldValue('L16') == 'TRUE')?"1":"0";
  var L17 = (block.getFieldValue('L17') == 'TRUE')?"1":"0";
  var L18 = (block.getFieldValue('L18') == 'TRUE')?"1":"0";
  var L19 = (block.getFieldValue('L19') == 'TRUE')?"1":"0";;
  var L20 = (block.getFieldValue('L20') == 'TRUE')?"1":"0";
  var L21 = (block.getFieldValue('L21') == 'TRUE')?"1":"0";
  var L22 = (block.getFieldValue('L22') == 'TRUE')?"1":"0";
  var L23 = (block.getFieldValue('L23') == 'TRUE')?"1":"0";
  var L24 = (block.getFieldValue('L24') == 'TRUE')?"1":"0";
  var L25 = (block.getFieldValue('L25') == 'TRUE')?"1":"0";
  var code = 'createMatrixLed('+L1+L2+L3+L4+L5+L6+L7+L8+L9+L10+L11+L12+L13+L14+L15+L16+L17+L18+L19+L20+L21+L22+L23+L24+L25+');';
  return code;
};
