Blockly.Msg.BLOCK1_SHOW = " DHT";
Blockly.Msg.VALUE_SHOW = "value";
Blockly.Msg.WIDTH_SHOW = "width";
Blockly.Msg.HEIGHT_SHOW = "height";
Blockly.Msg.TITLE_X_SHOW = "title_x";
Blockly.Msg.TITLE_Y_SHOW = "title_y";
Blockly.Msg.BLOCK2_SHOW = " Check Dataset";
Blockly.Msg.DATASET_SHOW = "DATASET";
Blockly.Msg.COUNT_SHOW = "COUNT";
